spring.application.name=project

# Primary Data Source 
#Source
spring.datasource.primary.jdbc-url=jdbc:oracle:thin:@//BRATUMVERSEDB01.BRITAMGROUP.COM:1521/OIPA
spring.datasource.primary.username=OIPA_PAS_Read
spring.datasource.primary.password=BrOIPA12#
spring.datasource.primary.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.primary.hikari.maximum-pool-size=10
# Secondary Data Source
#Target
spring.datasource.secondary.jdbc-url=jdbc:oracle:thin:@//10.10.3.246:1521/OIPAUAT
spring.datasource.secondary.username=OIPA_PAS
spring.datasource.secondary.password=OIPA_PAS
spring.datasource.secondary.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.secondary.hikari.maximum-pool-size=10

### dev data base

spring.datasource.secondary-dev.jdbc-url=jdbc:oracle:thin:@//10.10.3.246:1521/OIPADEVDB
spring.datasource.secondary-dev.username=OIPA_PAS
spring.datasource.secondary-dev.password=OIPA_PAS
spring.datasource.secondary-dev.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.secondary-dev.hikari.maximum-pool-size=10

# JPA Properties
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

server.port=8015

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

